language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.3
before_script:
script: 
  - rm composer.lock
  - composer install
  - composer require php-coveralls/php-coveralls
  - mkdir -p build/logs
  - vendor/bin/phpunit
after_success:
  - vendor/bin/php-coveralls -v
notifications:
  on_success: never
  on_failure: always
